name: Deploy site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "package.json"
      - "package-lock.json"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "package.json"
      - "package-lock.json"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write
  pages: write # Needed for deploying to GitHub Pages
  id-token: write # Needed for deploying to GitHub Pages

jobs:
  # Build job
  build:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*' # Or a specific version if al-folio targets one
          cache: 'npm'
      # - name: Cache Jupyter Notebook Conversions
      #   uses: actions/cache@v4
      #   with:
      #     # The directory to cache.
      #     path: _jupyter_cache
      #     # The key for the cache. It's based on the hash of your notebook file(s).
      #     # If the notebook changes, the hash changes, and the cache is invalidated.
      #     key: ${{ runner.os }}-jupyter-${{ hashFiles('**/blog.ipynb') }}
      #     # A key to restore from if the exact key isn't found.
      #     restore-keys: |
      #       ${{ runner.os }}-jupyter-
      # - name: Setup Python 🐍
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"
      #     cache: "pip" # caching pip dependencies
      - name: Debug file content 🐛
        run: |
          echo "--- Contents of _data/cv.yml before build ---"
          cat _data/cv.yml
          echo "-------------------------------------------"
      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade ipython
          npm ci
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace
          npm run css:purge
      - name: Upload artifact 🚀
        # Uploads the _site directory as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
